# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

# Do not build tags; it is redundant.
if: tag IS blank

language: node_js
node_js:
 - '10'
 - '8'

cache:
  directories:
    - $HOME/.npm
    - node_modules

# If you update the version of npm, update docker/Dockerfile too:
# https://www.npmjs.com/package/npm
before_install:
  - npm install --global npm@6.9.0

install: ./scripts/install.sh
