# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

# Do not build tags; it is redundant.
if: tag IS blank

language: node_js
node_js:
 - '14'
 - '12'
 - '10'

before_install:
  - ./dev.sh install-globals

install: ./dev.sh install
