# https://web.archive.org/web/20211009002551/https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python
name: Node.js CI

on:
  push:
    branches: [ main, update ]
  pull_request:
    branches: [ main, update ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}.
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./dev.sh install-globals
      - name: Install dependencies.
        run: npm ci
      - run: ./dev.sh install
      - run: npm run build --if-present
      - run: npm test
